
"use client";
import './globals.css';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef } from "react";
import StyledComponentsRegistry from '../lib/AntdRegistry';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // let pathName = usePathname();
  const router = useRouter();
  let pathName = usePathname();
  const searchParams = useSearchParams();
  // Add your own authentication on the below line.
  let isLoggedIn = useRef(false);

  useEffect(() => {
    isLoggedIn.current = localStorage.getItem('token') ? true : false; //AuthService.isLoggedIn()
    console.log(isLoggedIn.current);
    if (isLoggedIn.current) {
      if (pathName === '/') router.replace('/video/videoList');
      else {
        const url = `${pathName}?${searchParams}`
        router.replace(url);
      }
    } else {
      router.replace('/login');
    }
  }, []);
  
  return (
    <html>
      <body suppressHydrationWarning={true}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
